# sidebar菜单
menu:
  首页: /
  归档: /archives
rss: /atom.xml

#删除下方的注释符号即可选择使用文字或图片
#logo_text: 你是个好人
#logo_image: logo.png

#菜单图标选项
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIcon
  首页: home
  home: home
  about: user
  categories: th
  schedule: calendar
  tag: tag
  tags: tag
  标签: tag
  archives: archive
  归档: archive
  站点地图: map
  sitemap: map
  时间轴: timer

#Options:default is round and rect is making button rect
btn_sidebar: rect
btn_readmore:
btn_nav:

#sidebar的文字信息
slogon:
- 当然是选择原谅她啊
- 她真的只是去蹭空调

#name: url
social:
  github: //github.com
  facebook: //facebook.com
  #twitter: //twitter.com
  #pinterest: //pinterest.com
  #linkedin:
  instagram:
  tumblr:

#Format: name: url
friendlinks:
  goodman: https://github.com/byoungd/goodman
  github: https://github.com/

excerpt_link: Read More

#文章缩略图选项，开启后如果没有在front-matter设置则使用默认demo图片
thumb: true

#archives页面的github用户名
git_name: byoungd


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

